# Generated by Django 5.1 on 2024-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonal',
            name='admin_response',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
