# Generated by Django 5.1 on 2024-10-13 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0002_alter_testimonal_admin_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonal',
            new_name='Testimonial',
        ),
        migrations.CreateModel(
            name='ApprovedTestimonial',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Testimonial',
                'verbose_name_plural': 'Approved Testimonials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testimonal.testimonial',),
        ),
        migrations.CreateModel(
            name='UnapprovedTestimonial',
            fields=[
            ],
            options={
                'verbose_name': 'Unapproved Testimonial',
                'verbose_name_plural': 'Unapproved Testimonials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testimonal.testimonial',),
        ),
    ]
