# Generated by Django 5.1 on 2024-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0004_alter_testimonial_options_testimonial_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='ratings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
