# Generated by Django 5.1 on 2024-10-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0005_alter_testimonial_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonal_text',
            new_name='testimonial_text',
        ),
    ]
