# Generated by Django 5.1 on 2024-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0006_rename_testimonal_text_testimonial_testimonial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='ratings',
            field=models.SmallIntegerField(),
        ),
    ]
