# Generated by Django 5.1 on 2024-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0008_testimonial_updated_on_alter_testimonial_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='has_admin_responded',
            field=models.BooleanField(default=False),
        ),
    ]
