# Generated by Django 5.1 on 2024-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0012_alter_testimonial_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='job_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_image',
            field=models.URLField(blank=True, null=True, verbose_name='User image url'),
        ),
    ]
