# Generated by Django 5.1 on 2024-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonal', '0013_remove_testimonial_title_testimonial_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_image',
            field=models.URLField(blank=True, null=True, verbose_name='User image url (optional)'),
        ),
    ]
