# Generated by Django 5.1 on 2024-10-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_billingaddress_is_primary_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_2',
        ),
    ]
