# Generated by Django 5.1 on 2024-09-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_address_date_created_address_modifed_giftcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='address',
            name='modifed',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
