# Generated by Django 5.1 on 2024-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_giftcard_date_created_userprofile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gift_card',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gift_cards',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='user_profile.giftcard'),
        ),
    ]
