# Generated by Django 5.1 on 2024-09-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_userprofile_gift_card_userprofile_gift_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
