# Generated by Django 5.1 on 2024-09-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_giftcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='does_not_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/cover/photo/', verbose_name='Cover picture'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/pic/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(blank=True, max_length=43, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
