# Generated by Django 5.1 on 2024-09-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_giftcard_does_not_expire_giftcard_is_redeemed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcard',
            options={'verbose_name': 'Issue gift card', 'verbose_name_plural': 'Issue gift cards'},
        ),
    ]
