# Generated by Django 5.1 on 2024-09-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_addresses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gift_cards',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_addresses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='user_profile.billingaddress'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gift_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='user_profile.giftcard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='user_profile.shippingaddress'),
        ),
    ]
