# Generated by Django 5.1 on 2024-09-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_alter_giftcard_options_alter_billingaddress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gift_cards',
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='user_profile.userprofile'),
        ),
    ]
