# Generated by Django 5.1 on 2024-09-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_userprofile_gift_cards_alter_giftcard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='user',
            new_name='user_profile',
        ),
    ]
