# Generated by Django 5.1 on 2024-09-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_remove_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
    ]
