# Generated by Django 5.1 on 2024-11-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='new_category',
        ),
        migrations.AddField(
            model_name='newpost',
            name='new_category',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
    ]
