# Generated by Django 5.1 on 2024-11-07 05:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_newpost_new_category_newpost_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='users/cover/blog/post/', verbose_name='main post image'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='post',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='New post'),
        ),
    ]
