# Generated by Django 5.1 on 2024-11-07 06:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newpost_cover_pic_alter_newpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='New post'),
        ),
    ]
