# Generated by Django 5.1 on 2024-11-07 06:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newpost_is_live_alter_newpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='New post'),
        ),
    ]
