# Generated by Django 5.1 on 2024-11-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_created_at_category_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
