# Generated by Django 5.1 on 2024-12-08 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvariation_maximum_stock_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Size (e.g s, m, l, xl)'),
        ),
    ]
