# Generated by Django 5.1 on 2024-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_shipping_created_on_shipping_modified_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='express_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='premium_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
