# Generated by Django 5.1 on 2024-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_shipping_express_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
