# Generated by Django 5.1 on 2025-01-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productvariation_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='is_discounted_price',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='standard_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
