# Generated by Django 5.1 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_discount_product_is_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='express_shipping',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='premium_shipping',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_height',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_length',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_width',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='standard_shipping',
        ),
        migrations.AddField(
            model_name='shipping',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shippng_type',
            field=models.CharField(choices=[('s', 'Standard'), ('e', 'Express'), ('p', 'Premium')], default='s'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
