# Generated by Django 5.1 on 2025-01-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_shipping_express_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
    ]
