# Generated by Django 5.1 on 2025-01-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_manufacturer_contact_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shippng_type',
            new_name='shipping_type',
        ),
    ]
