# Generated by Django 5.1 on 2025-01-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_sku_alter_product_upc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='availability',
            field=models.CharField(choices=[('IS', 'In Stock'), ('OO', 'Out of Stock'), ('PO', 'Pre-order')], default='IS', max_length=2),
        ),
    ]
