# Generated by Django 5.1 on 2025-01-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productvariation_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='availability',
            field=models.CharField(choices=[('is', 'In Stock'), ('oo', 'Out of Stock'), ('po', 'Pre-order')], default='is', max_length=2),
        ),
    ]
