# Generated by Django 5.1 on 2025-01-10 02:14

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
