# Generated by Django 5.1 on 2025-01-15 00:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_category_alter_manufacturer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
