# Generated by Django 5.1 on 2025-01-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_manufacturer_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(max_length=255),
        ),
    ]
