# Generated by Django 5.1 on 2025-01-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
