# Generated by Django 5.1 on 2024-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is email verified')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
