# Generated by Django 5.1 on 2024-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
