# Generated by Django 5.1 on 2024-09-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_verification_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Active User',
                'verbose_name_plural': 'Active Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='AdminUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='BannedUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Banned User',
                'verbose_name_plural': 'Banned Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='NonActiveUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Non-active User',
                'verbose_name_plural': 'Non-active Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='StaffUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Staff User',
                'verbose_name_plural': 'Staff Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='SuperUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='VerifiedUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Verified User',
                'verbose_name_plural': 'Verified Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
    ]
