# Generated by Django 5.1 on 2024-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_last_token_generated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_token_generated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
