# Generated by Django 5.1 on 2024-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_activeuserproxy_adminuserproxy_banneduserproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temp_ban',
            field=models.BooleanField(default=False, verbose_name='is_temp_ban'),
        ),
    ]
