# Generated by Django 5.1 on 2024-09-14 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_ban_reason_user_banned_data_user_is_temp_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='banned_data',
        ),
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_reason', models.CharField(max_length=255)),
                ('ban_expires_on', models.DateTimeField()),
                ('date_ban_was_issued', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
