# Generated by Django 5.1 on 2025-01-21 17:23

import django.db.models.deletion
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_banuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(db_index=True, verbose_name='Client IP Address')),
                ('local_ip', models.GenericIPAddressField(default=utils.utils.get_local_ip_address, verbose_name='Local Device IP Address')),
                ('frontend_timezone', models.CharField(db_index=True, max_length=255, verbose_name='Frontend Time Zone')),
                ('backend_timezone', models.CharField(db_index=True, max_length=255, verbose_name='Backend Time Zone')),
                ('user_agent', models.CharField(db_index=True, max_length=1000, verbose_name='User Agent')),
                ('screen_width', models.PositiveSmallIntegerField(db_index=True)),
                ('screen_height', models.PositiveSmallIntegerField(db_index=True)),
                ('platform', models.CharField(max_length=255, verbose_name='Device Platform')),
                ('pixel_ratio', models.CharField(db_index=True, max_length=255)),
                ('is_touch_device', models.BooleanField(default=False, verbose_name='Is Touchscreen Device')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login Time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
