# Generated by Django 5.1 on 2024-09-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_ban_reason_remove_user_banned_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='ban_reason',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='banuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
    ]
