# Generated by Django 5.1 on 2025-01-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'User Device', 'verbose_name_plural': 'User Devices'},
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='client_ip',
        ),
    ]
