# Generated by Django 5.1 on 2024-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_banuser_ban_reason_alter_banuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
