# Generated by Django 5.1 on 2025-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userdevice_options_remove_userdevice_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='broswer_version',
            field=models.CharField(db_index=True, default='131.0', max_length=255),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='browser',
            field=models.CharField(db_index=True, default='Chrome', max_length=255),
        ),
    ]
