# Generated by Django 5.1 on 2024-09-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_banuser_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banuser',
            old_name='modified',
            new_name='modified_on',
        ),
    ]
