# Generated by Django 5.1 on 2025-01-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userdevice_broswer_version_userdevice_browser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='broswer_version',
            new_name='browser_version',
        ),
    ]
