# Generated by Django 5.1 on 2024-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_modified_banuser_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='date_ban_was_issued',
            field=models.DateTimeField(),
        ),
    ]
