# Generated by Django 5.1 on 2025-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_broswer_version_userdevice_browser_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='browser',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='browser_version',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
