# Generated by Django 5.1 on 2024-09-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_banuser_date_ban_was_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBannedUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Temporary Banned User',
                'verbose_name_plural': 'Temporary Banned Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.RenameField(
            model_name='banuser',
            old_name='date_ban_was_issued',
            new_name='ban_start_date',
        ),
    ]
