# Generated by Django 5.1 on 2025-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_userdevice_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='browser',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='browser_version',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='pixel_ratio',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='platform',
            field=models.CharField(max_length=255, verbose_name='Operating System'),
        ),
    ]
