# Generated by Django 5.1 on 2025-01-22 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_userdevice_device_alter_userdevice_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=40, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='pixel_ratio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='screen_height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='screen_width',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['client_ip_address', 'timestamp'], name='authenticat_client__d97eba_idx'), models.Index(fields=['country', 'region'], name='authenticat_country_40009c_idx')],
            },
        ),
    ]
