# Generated by Django 5.1 on 2025-01-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='authenticat_country_40009c_idx',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='city',
            field=models.CharField(db_index=True, default='London', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='host_name',
            field=models.CharField(default='Superbase', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='organization',
            field=models.CharField(default='Kitoye', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['country', 'region', 'city'], name='authenticat_country_329a2f_idx'),
        ),
    ]
