# Generated by Django 5.1 on 2025-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='authenticat_country_40009c_idx',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='city',
            field=models.CharField(db_index=True, default='London', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='host_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='backend_timezone',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Backend Time Zone'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='frontend_timezone',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Frontend Time Zone'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='platform',
            field=models.CharField(max_length=50, verbose_name='Operating System'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['country', 'region', 'city'], name='authenticat_country_329a2f_idx'),
        ),
    ]
