# Generated by Django 5.1 on 2024-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_banuser_ban_expires_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='ban_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banuser',
            name='ban_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
