# Generated by Django 5.1 on 2025-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_loginattempt_authenticat_country_40009c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='host_name',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
