# Generated by Django 5.1 on 2025-01-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_loginattempt_host_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='org',
        ),
    ]
