# Generated by Django 5.1 on 2025-01-23 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_loginattempt_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseLineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip_address', models.GenericIPAddressField(db_index=True)),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Baseline Data',
                'verbose_name_plural': 'Users Baseline Data',
            },
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='authenticat_client__d97eba_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='authenticat_country_329a2f_idx',
        ),
        migrations.AddField(
            model_name='userbaselinedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_baseline', to=settings.AUTH_USER_MODEL),
        ),
    ]
