# Generated by Django 5.1 on 2025-01-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_userbaselinedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaselinedata',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='client_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
