# Generated by Django 5.1 on 2025-01-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_userbaselinedata_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbaselinedata',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
