# Generated by Django 5.1 on 2025-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_userbaselinedata_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device',
            field=models.CharField(db_index=True, max_length=80, null=True),
        ),
    ]
