# Generated by Django 5.1 on 2025-01-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_userdevice_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaselinedata',
            name='client_ip_address',
            field=models.TextField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
