# Generated by Django 5.1 on 2025-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_userbaselinedata_client_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='backend_timezone',
        ),
        migrations.AlterField(
            model_name='userbaselinedata',
            name='client_ip_address',
            field=models.TextField(blank=True, db_index=True, max_length=64, null=True, verbose_name='hashed ip address'),
        ),
    ]
