# Generated by Django 5.1 on 2025-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_userdevice_backend_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='pixel_ratio',
            field=models.FloatField(max_length=50),
        ),
    ]
