# Generated by Django 5.1 on 2024-10-22 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly'), ('BW', 'Bi-weekly'), ('m', 'Montly'), ('q', 'Quartely')], default='m', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
