# Generated by Django 5.1 on 2024-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_newslettersubscription_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedNewsletterSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Subscribed Newsletter Subscription',
                'verbose_name_plural': 'Subscribed Newsletter Subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscription.newslettersubscription',),
        ),
        migrations.CreateModel(
            name='UnsubscribedNewsletterSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Unsubscribed Newsletter Subscription',
                'verbose_name_plural': 'Unsubscribed Newsletter Subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscription.newslettersubscription',),
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'All Newsletter Subscription', 'verbose_name_plural': 'All Newsletter Subscriptions'},
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='reason_for_unsubscribing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='unsubscribed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
