# Generated by Django 5.1 on 2024-10-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_newslettersubscription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriptionhistory',
            name='unsubscribed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='frequency',
            field=models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly'), ('bw', 'Bi-weekly'), ('m', 'Monthly'), ('q', 'Quarterly')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='newslettersubscriptionhistory',
            name='frequency',
            field=models.CharField(blank=True, choices=[('d', 'Daily'), ('w', 'Weekly'), ('bw', 'Bi-weekly'), ('m', 'Monthly'), ('q', 'Quarterly')], max_length=2, null=True),
        ),
    ]
