# Generated by Django 5.1 on 2024-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_newslettersubscriptionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriptionhistory',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriptionhistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
