# Generated by Django 5.1 on 2024-11-06 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_newslettersubscriptionhistory_modified_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='unsubscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
